# Blog
keywords: Hexo,HTML,CSS,android,Linux
author: Author Name,name@example.com
description: Nothing lasts forever.
avatar: https://avatars2.githubusercontent.com/u/13299413?s=460&v=4

# Social Accounts
twitter: 
rss: 
weibo: 
instagram: 
github: 
facebook: 

# Comment
duoshuo: 
disqus: 
gentie: 
